version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sudu_django
      - POSTGRES_PASSWORD=sudu_django
      - POSTGRES_DB=sudu_django_dev

volumes:
  postgres_data: