# Generated by Django 2.2.6 on 2019-12-07 01:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='festival',
            name='current_year_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Current year date'),
        ),
        migrations.AddField(
            model_name='festival',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AddField(
            model_name='festival',
            name='has_rental_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='festival',
            name='is_african',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='festival',
            name='is_competitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='festival',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='month_occurence',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Periode'),
        ),
        migrations.AddField(
            model_name='festival',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='support',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
