# Generated by Django 2.2.10 on 2020-11-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='isCompetitive',
            field=models.BooleanField(default=False),
        ),
    ]
