# Generated by Django 2.2.10 on 2020-11-13 07:10

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='isRescheduled',
            field=models.BooleanField(default=False, verbose_name='is rescheduled'),
        ),
        migrations.AddField(
            model_name='festival',
            name='rescheduledDate',
            field=models.DateField(blank=True, null=True, verbose_name='Rescheduled Date'),
        ),
        migrations.AddField(
            model_name='projection',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='projection',
            name='dateEndPeriod',
            field=models.DateField(blank=True, null=True, verbose_name='End period'),
        ),
        migrations.AddField(
            model_name='projection',
            name='dateStartPeriod',
            field=models.DateField(blank=True, null=True, verbose_name='Start period'),
        ),
        migrations.AddField(
            model_name='projection',
            name='presenceType',
            field=models.CharField(choices=[('ONLINE', 'On-line'), ('PHYSICAL', 'Physique'), ('BOTH', 'Online+Physique')], default='PHYSICAL', max_length=20, verbose_name='In person/remote'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='presenceType',
            field=models.CharField(choices=[('ONLINE', 'On-line'), ('PHYSICAL', 'Physique'), ('BOTH', 'Online+Physique')], default='PHYSICAL', max_length=20, verbose_name='In person/remote'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Film title'),
        ),
        migrations.AlterField(
            model_name='film',
            name='productionYear',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='Production Year'),
        ),
        migrations.AlterField(
            model_name='projection',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Projection Date'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime.now, verbose_name='Inscription Date'),
        ),
    ]
