# Generated by Django 2.2.10 on 2020-11-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20201113_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='billSent',
            field=models.BooleanField(default=False, verbose_name='Bill sent'),
        ),
        migrations.AddField(
            model_name='projection',
            name='festival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.Festival'),
        ),
        migrations.AddField(
            model_name='projection',
            name='isCancel',
            field=models.BooleanField(default=False, verbose_name='Cancel'),
        ),
        migrations.AddField(
            model_name='projection',
            name='isRescheduled',
            field=models.BooleanField(default=False, verbose_name='is rescheduled'),
        ),
        migrations.AddField(
            model_name='projection',
            name='mediaSent',
            field=models.BooleanField(default=False, verbose_name='Media sent'),
        ),
        migrations.AddField(
            model_name='projection',
            name='paymentReceived',
            field=models.BooleanField(default=False, verbose_name='Payment received'),
        ),
        migrations.AddField(
            model_name='projection',
            name='quoteSent',
            field=models.BooleanField(default=False, verbose_name='Quote sent'),
        ),
        migrations.AddField(
            model_name='projection',
            name='rescheduledDate',
            field=models.DateField(blank=True, null=True, verbose_name='Rescheduled Date'),
        ),
        migrations.AddField(
            model_name='projection',
            name='socialMediaNotified',
            field=models.BooleanField(default=False, verbose_name='Social media notified'),
        ),
        migrations.AddField(
            model_name='projection',
            name='supportChoices',
            field=models.CharField(choices=[('HDFTP', 'HD FTP'), ('DD', 'DD'), ('NAS', 'Nas'), ('DCP DD', 'DCP DD'), ('SMASH', 'Smash'), ('DVD', 'DVD')], default='HDFTP', max_length=20, verbose_name='Projection support'),
        ),
        migrations.AlterField(
            model_name='film',
            name='filmType',
            field=models.CharField(choices=[('DOCU', 'Documentaire'), ('FICTION', 'Fiction'), ('SHORT', 'Court-Métrage'), ('XP', 'Experimental')], default='FICTION', max_length=20),
        ),
    ]
