# Generated by Django 2.2.8 on 2019-12-09 01:59

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_manual_20191208_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster'),
        ),
    ]
