# Generated by Django 2.2.10 on 2020-11-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20201115_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='film',
        ),
        migrations.AddField(
            model_name='projection',
            name='films',
            field=models.ManyToManyField(to='cinema.Film'),
        ),
    ]
