# Generated by Django 2.2.10 on 2020-11-16 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20201115_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=100, verbose_name='Structure')),
                ('name', models.CharField(max_length=100, verbose_name='Event name')),
                ('deadlineMediaReception', models.DateField(blank=True, null=True, verbose_name='Media reception date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='festival',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='projection',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projection',
            name='quotedPrice',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Quoted price'),
        ),
        migrations.AlterField(
            model_name='projection',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.Festival'),
        ),
        migrations.AlterField(
            model_name='projection',
            name='location',
            field=models.CharField(max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='projection',
            name='supportChoices',
            field=models.CharField(choices=[('HDFTP', 'HD FTP'), ('DD', 'DD'), ('NAS', 'Nas'), ('DCP DD', 'DCP DD'), ('SMASH', 'Smash'), ('DVD', 'DVD'), ('.MOV', '.MOV'), ('BLURAY', 'Blu-ray')], default='HDFTP', max_length=20, verbose_name='Projection support'),
        ),
        migrations.AddField(
            model_name='projection',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.Event'),
        ),
    ]
