# Generated by Django 2.2.10 on 2021-02-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20201116_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='duration',
        ),
        migrations.AddField(
            model_name='submission',
            name='isCompetitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='productionYear',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='Production Year'),
        ),
    ]
