# Generated by Django 2.2.10 on 2021-02-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20210201_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='isPartOfSelection',
            field=models.BooleanField(default=False, verbose_name='Selection'),
        ),
        migrations.AlterField(
            model_name='film',
            name='filmType',
            field=models.CharField(choices=[('DOCU', 'Documentaire'), ('FICTION', 'Fiction'), ('SHORT', 'Court-Métrage'), ('XP', 'Experimental'), ('ANIMATION', 'Animation')], default='FICTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='isCompetitive',
            field=models.BooleanField(default=False, verbose_name='is Part of festival competitive selection?'),
        ),
    ]
