# Generated by Django 2.2.10 on 2021-02-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_auto_20210201_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='projections',
            field=models.ManyToManyField(blank=True, to='cinema.Projection'),
        ),
        migrations.AlterField(
            model_name='projection',
            name='films',
            field=models.ManyToManyField(blank=True, to='cinema.Film'),
        ),
    ]
