# Generated by Django 5.2.13 on 2026-04-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_event_id_alter_festival_id_alter_film_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fee in Euros'),
        ),
    ]
