# Generated by Django 2.2.9 on 2020-02-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_auto_20200111_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='date',
            new_name='dateSubmission',
        ),
        migrations.AddField(
            model_name='submission',
            name='responseDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Periode'),
        ),
    ]
