# Generated by Django 2.2.9 on 2020-02-03 02:13

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_auto_20200203_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='response',
            field=models.CharField(choices=[(cinema.models.ResponseChoice('Selectionned'), 'Selectionned'), (cinema.models.ResponseChoice('Refused'), 'Refused'), (cinema.models.ResponseChoice('No response yet'), 'No response yet')], default=cinema.models.ResponseChoice('No response yet'), max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submission Date'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='responseDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Response Date'),
        ),
    ]
