# Generated by Django 2.2.9 on 2020-02-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_auto_20200203_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='current_year_date',
            field=models.DateField(blank=True, null=True, verbose_name='Current year date'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='month_occurence',
            field=models.DateField(blank=True, null=True, verbose_name='Periode'),
        ),
        migrations.AlterField(
            model_name='projection',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Periode'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(blank=True, null=True, verbose_name='Submission Date'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='response',
            field=models.CharField(choices=[('SELECTIONED', 'Selectionned'), ('REFUSED', 'Refused'), ('NO_RESPONSE', 'No response yet')], default='NO_RESPONSE', max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='responseDate',
            field=models.DateField(blank=True, null=True, verbose_name='Response Date'),
        ),
    ]
