# Generated by Django 2.2.9 on 2020-02-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_festival_month_occurence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='dateSubmission',
        ),
    ]
