# Generated by Django 2.2.9 on 2020-02-04 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_remove_submission_datesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 2, 4, 3, 57, 2, 830008), verbose_name='Submission Date'),
            preserve_default=datetime.datetime(2020, 2, 4, 3, 57, 2, 830008),
        ),
    ]
