# Generated by Django 2.2.9 on 2020-03-08 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_submission_datesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 3, 8, 19, 26, 4, 614422), verbose_name='Submission Date'),
        ),
    ]
