# Generated by Django 2.2.9 on 2020-03-08 21:40

import cinema.models
import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_auto_20200308_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='country',
            field=django_countries.fields.CountryField(countries=cinema.models.G8Countries, default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='festival',
            name='current_year_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 3, 8, 21, 40, 37, 550122), verbose_name='Submission Date'),
        ),
    ]
