# Generated by Django 2.2.9 on 2020-03-08 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_auto_20200308_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='deadline_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 3, 8, 21, 42, 16, 746034), verbose_name='Submission Date'),
        ),
    ]
