# Generated by Django 2.2.9 on 2020-03-08 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_auto_20200308_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='month_occurence',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(111, 'Year Round'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='support',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 3, 8, 23, 18, 10, 773458), verbose_name='Submission Date'),
        ),
    ]
