# Generated by Django 2.2.9 on 2020-03-08 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_auto_20200308_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='support',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 3, 8, 23, 19, 48, 716845), verbose_name='Submission Date'),
        ),
    ]
