# Generated by Django 2.2.9 on 2020-03-09 02:13

import cinema.models
import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_auto_20200308_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='country',
            field=django_countries.fields.CountryField(countries=cinema.models.G8Countries, max_length=2),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 3, 9, 2, 13, 42, 222448), verbose_name='Submission Date'),
        ),
    ]
