# Generated by Django 2.2.10 on 2020-04-21 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_auto_20200309_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 4, 21, 23, 30, 46, 695757), verbose_name='Submission Date'),
        ),
    ]
