# Generated by Django 2.2.10 on 2020-10-21 01:27

import cinema.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0022_auto_20200421_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('frenchTemplate', models.FileField(blank=True, null=True, storage=cinema.models.OverwriteStorage(), upload_to=cinema.models.SiteConfiguration.lang_path_fr)),
                ('englishTemplate', models.FileField(blank=True, null=True, storage=cinema.models.OverwriteStorage(), upload_to=cinema.models.SiteConfiguration.lang_path_en)),
            ],
            options={
                'verbose_name': 'Reports Configuration',
            },
        ),
        migrations.AddField(
            model_name='festival',
            name='inscriptions',
            field=models.ManyToManyField(related_name='festivals', through='cinema.Submission', to='cinema.Film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='productionYear',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 10, 21, 1, 27, 6, 619816), verbose_name='Submission Date'),
        ),
    ]
