# Generated by Django 2.2.10 on 2020-04-23 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0023_auto_20200423_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 4, 23, 23, 28, 53, 8199), verbose_name='Submission Date'),
        ),
    ]
