# Generated by Django 2.2.10 on 2020-10-21 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0024_auto_20201021_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 10, 21, 1, 29, 38, 790422), verbose_name='Submission Date'),
        ),
    ]
