# Generated by Django 2.2.10 on 2020-04-23 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0024_auto_20200423_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Reports Configuration'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='englishTemplate',
            field=models.FileField(blank=True, null=True, upload_to='reportTemplate/fr'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='frenchTemplate',
            field=models.FileField(blank=True, null=True, upload_to='reportTemplate/fr'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 4, 23, 23, 35, 16, 550876), verbose_name='Submission Date'),
        ),
    ]
