# Generated by Django 2.2.10 on 2020-04-24 03:43

import cinema.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0025_auto_20200423_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='englishTemplate',
            field=models.FileField(blank=True, null=True, upload_to=cinema.models.SiteConfiguration.lang_path_en),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='frenchTemplate',
            field=models.FileField(blank=True, null=True, upload_to=cinema.models.SiteConfiguration.lang_path_fr),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dateSubmission',
            field=models.DateField(null=datetime.datetime(2020, 4, 24, 3, 43, 19, 120790), verbose_name='Submission Date'),
        ),
    ]
