###########
# BUILDER #
###########

FROM python:3.13-alpine AS builder

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev libc-dev libxslt-dev \
    && apk add postgresql-dev \
    && apk add jpeg-dev zlib-dev libjpeg \
    && apk add libxslt

# Install UV
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Lint
RUN uv pip install --system flake8
COPY . /usr/src/app/
RUN flake8 --ignore=E501,F401 .

# Build wheels
COPY ./pyproject.toml .
RUN uv pip install --system pip setuptools wheel
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r <(uv pip compile pyproject.toml)


#########
# FINAL #
#########

FROM python:3.13-alpine

RUN mkdir -p /home/app

RUN addgroup -S app && adduser -S app -G app

ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# Install runtime dependencies
RUN apk update && apk add libpq libjpeg libxslt
COPY --from=builder /usr/src/app/wheels /wheels
RUN pip install --upgrade pip
RUN pip install --no-cache /wheels/*

# Copy entrypoint
COPY ./entrypoint.prod.sh $APP_HOME

# Copy project
COPY . $APP_HOME

RUN chown -R app:app $APP_HOME

USER app

ENTRYPOINT ["/home/app/web/entrypoint.prod.sh"]
